### ISSUE TITLE
Check if images post to database

### ISSUE THREAD

**Issue by RoujiaW** [EricaSkerrett/bme590final#85]
Some issues with post processed images functions
Traceback (most recent call last):
  File "gui.py", line 345, in compression
    self.next = App5()
  File "gui.py", line 381, in __init__
    self.init_gui()
  File "gui.py", line 391, in init_gui
    self.display_images()
  File "gui.py", line 402, in display_images
    global_user_email, global_selected_name, global_process_type)
  File "/Users/rosesharpaywang/Desktop/BME590Palmeri/bme590final/client.py", line 147, in get_processed_image
    processed_image = r.json()
  File "/Users/rosesharpaywang/Desktop/BME590Palmeri/bme590final/.venv/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Abort trap: 6

**Comment by sputney13** [comment]
Resolved with #96 !
